### ISSUE TITLE
Unresolved symbol bmx_git_AnyUncommittedChanges / bmx_git_Describe / bmx_git_DescribeTag

### ISSUE THREAD

**Issue by jonno85uk** [bbc/bmx#14]
I have successfully built bmx on windows with the following commands:
`bmx\build> cmake -G "Visual Studio 15 2017 Win64" ..`
`cmake --build . --config Release --target install`

However, when it comes to linking the libraries I have 6 unresolved symbols.

![bmx](https://github.com/bbc/bmx/assets/14606456/69c61567-4dbe-4bd9-b2e0-056d9b44aa3e)

A search of the codebase finds the use of these functions in various places but I cannot find the implementation of them in any of the source files but instead a patch cmake\git_version_904dbda.patch

Is there a step missing in the build instructions?

**Comment by philipnbbc** [comment]
The git version tracking implementation comes from https://github.com/andrew-hardin/cmake-git-version-tracking.git, gets brought in by https://github.com/bbc/bmx/blob/main/cmake/git_version.cmake and linked at https://github.com/bbc/bmx/blob/main/src/CMakeLists.txt#L80. There should be a `_deps` directory in the build directory containing the git tracking code.

I would think then that those functions are internal to the static bmx.lib given that your bmx build succeeded, which includes the apps (e.g. bmxtranswrap) that link to the bmx.lib.

I should have some time tomorrow to take a closer look to try understand why it isn't working as expected.

**Comment by jonno85uk** [comment]
After looking through the build log I discovered 2 libs which looked potentially relevant

bmx\build\_deps\bmx_git_version-build\Release\bmx_git_version.lib

and 

bmx\build\_deps\libmxfpp_git_version-build\Release\libmxfpp_git_version.lib

These were not in the lib directory of the install. I copied them over and the symbols were resolved.

**Comment by jonno85uk** [comment]
Ah, yes. I have copied over libmxf_git_version.lib, not libmxfpp_git_version.lib

**Comment by philipnbbc** [comment]
bmx.lib should depend on those symbols, but it then depends on MXF and MXFpp libraries which then depend on symbols from libmxf_git_version.lib and libmxf_git_version.lib respectively.

I can't check myself atm, but I'm assuming that the build logs show those git_version.libs in the list of libraries linked into the executables (mxf2raw, bmxtranswrap, raw2bmx). This confirms why the build works for the executables and why you've needed to do the same.

**Comment by philipnbbc** [comment]
I've fixed it in https://github.com/bbc/bmx/pull/16 by including the git version objects in the library rather than requiring a link to a separate library file.
