### ISSUE TITLE
XAVC Intra Class 100 50p files with BT2020 matrix are erroneously being flagged as BT709

### ISSUE THREAD

**Issue by FranceBB** [bbc/bmx#28]
As simple as that, when an XAVC Intra Class 100 50p file with BT2020nc matrix, BT2020 primaries and HLG (arib-std-b67) transfer in both the codec header and the container is remuxed with BMX Transwrap 1.1.0.0.0, the matrix gets erroneously changed to BT709.

How to reproduce:
- Take a BT2020 XAVC Intra Class 100 50p file
- Remux with the following BMX Transwrap command

`bmxtranswrap.exe -p -y 00:00:00:00 -t op1a --track-map stereo -o "Test_BBC_BMX.mxf" "Test_Omneon.mxf"`

- Check the mediainfo of the container being erroneously changed by BMX.

Sample (Source & Remuxed files): https://we.tl/t-jRK6xnR1Ky

Mediainfo of the source:

<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>General</H2></TD></TR>
<TR>
<TD><I>Complete name :</I></TD>
<TD colSpan=3>A:\MEDIA\temp\Test_Omneon.mxf</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MXF</TD></TR>
<TR>
<TD><I>Format version :</I></TD>
<TD colSpan=3>1.3</TD></TR>
<TR>
<TD><I>Format profile :</I></TD>
<TD colSpan=3>OP-1a</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>Closed / Complete</TD></TR>
<TR>
<TD><I>File size :</I></TD>
<TD colSpan=3>55.9 MiB</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Overall bit rate :</I></TD>
<TD colSpan=3>235 Mb/s</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Encoded date :</I></TD>
<TD colSpan=3>2023-08-29 11:21:12.380</TD></TR>
<TR>
<TD><I>Writing application :</I></TD>
<TD colSpan=3>Omneon Inc. Omneon Media Subsystem 9.8.0.0.1</TD></TR>
<TR>
<TD><I>Writing library :</I></TD>
<TD colSpan=3>Omneon Media Api (windows)</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Video</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>2</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>AVC</TD></TR>
<TR>
<TD><I>Format/Info :</I></TD>
<TD colSpan=3>Advanced Video Codec</TD></TR>
<TR>
<TD><I>Format profile :</I></TD>
<TD colSpan=3>High 4:2:2 Intra@L5.2</TD></TR>
<TR>
<TD><I>Format settings, CABAC :</I></TD>
<TD colSpan=3>No</TD></TR>
<TR>
<TD><I>Format settings, GOP :</I></TD>
<TD colSpan=3>N=1</TD></TR>
<TR>
<TD><I>Format settings, wrapping mode :</I></TD>
<TD colSpan=3>Frame</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>0D01030102106001-0401020201323104</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>228 Mb/s</TD></TR>
<TR>
<TD><I>Width :</I></TD>
<TD colSpan=3>1 920 pixels</TD></TR>
<TR>
<TD><I>Height :</I></TD>
<TD colSpan=3>1 080 pixels</TD></TR>
<TR>
<TD><I>Display aspect ratio :</I></TD>
<TD colSpan=3>16:9</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Standard :</I></TD>
<TD colSpan=3>Component</TD></TR>
<TR>
<TD><I>Color space :</I></TD>
<TD colSpan=3>YUV</TD></TR>
<TR>
<TD><I>Chroma subsampling :</I></TD>
<TD colSpan=3>4:2:2</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>10 bits</TD></TR>
<TR>
<TD><I>Scan type :</I></TD>
<TD colSpan=3>Progressive</TD></TR>
<TR>
<TD><I>Bits/(Pixel*Frame) :</I></TD>
<TD colSpan=3>2.195</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>54.3 MiB (97%)</TD></TR>
<TR>
<TD><I>Color range :</I></TD>
<TD colSpan=3>Limited</TD></TR>
<TR>
<TD><I>Color primaries :</I></TD>
<TD colSpan=3>BT.2020</TD></TR>
<TR>
<TD><I>Transfer characteristics :</I></TD>
<TD colSpan=3>HLG</TD></TR>
<TR>
<TD><I>Matrix coefficients :</I></TD>
<TD colSpan=3>BT.2020 non-constant</TD></TR>
<TR>
<TD><I>Delay_SystemScheme1 :</I></TD>
<TD colSpan=3>0</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Audio</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>3</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>PCM</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>Little</TD></TR>
<TR>
<TD><I>Format settings, wrapping mode :</I></TD>
<TD colSpan=3>Frame (BWF)</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>0D01030102060100</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Bit rate mode :</I></TD>
<TD colSpan=3>Constant</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>6 912 kb/s</TD></TR>
<TR>
<TD><I>Channel(s) :</I></TD>
<TD colSpan=3>6 channels</TD></TR>
<TR>
<TD><I>Sampling rate :</I></TD>
<TD colSpan=3>48.0 kHz</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS (960 SPF)</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>24 bits</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>1.65 MiB (3%)</TD></TR>
<TR>
<TD><I>Delay_SystemScheme1 :</I></TD>
<TD colSpan=3>0</TD></TR>
<TR>
<TD><I>Locked :</I></TD>
<TD colSpan=3>Yes</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Other #1</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1-Material</TD></TR>
<TR>
<TD><I>Type :</I></TD>
<TD colSpan=3>Time code</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MXF TC</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Time code of first frame :</I></TD>
<TD colSpan=3>00:00:00:00</TD></TR>
<TR>
<TD><I>Time code of last frame :</I></TD>
<TD colSpan=3>00:00:01:49</TD></TR>
<TR>
<TD><I>Time code settings :</I></TD>
<TD colSpan=3>Material Package</TD></TR>
<TR>
<TD><I>Time code, stripped :</I></TD>
<TD colSpan=3>Yes</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Other #2</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1-Source</TD></TR>
<TR>
<TD><I>Type :</I></TD>
<TD colSpan=3>Time code</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MXF TC</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Time code of first frame :</I></TD>
<TD colSpan=3>00:00:00:00</TD></TR>
<TR>
<TD><I>Time code of last frame :</I></TD>
<TD colSpan=3>00:00:01:49</TD></TR>
<TR>
<TD><I>Time code settings :</I></TD>
<TD colSpan=3>Source Package</TD></TR>
<TR>
<TD><I>Time code, stripped :</I></TD>
<TD colSpan=3>Yes</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Other #3</H2></TD></TR>
<TR>
<TD><I>Type :</I></TD>
<TD colSpan=3>Time code</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>SMPTE TC</TD></TR>
<TR>
<TD><I>Muxing mode :</I></TD>
<TD colSpan=3>System scheme 1</TD></TR>
<TR>
<TD><I>Time code of first frame :</I></TD>
<TD colSpan=3>00:00:00:00</TD></TR></TBODY></TABLE><BR>

Mediainfo of the remuxed file:

<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>General</H2></TD></TR>
<TR>
<TD><I>Complete name :</I></TD>
<TD colSpan=3>A:\MEDIA\temp\Test_BBC_BMX.mxf</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MXF</TD></TR>
<TR>
<TD><I>Format version :</I></TD>
<TD colSpan=3>1.3</TD></TR>
<TR>
<TD><I>Format profile :</I></TD>
<TD colSpan=3>OP-1a</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>Closed / Complete</TD></TR>
<TR>
<TD><I>File size :</I></TD>
<TD colSpan=3>55.9 MiB</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Overall bit rate :</I></TD>
<TD colSpan=3>235 Mb/s</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Encoded date :</I></TD>
<TD colSpan=3>2023-08-29 11:23:12.740</TD></TR>
<TR>
<TD><I>Writing application :</I></TD>
<TD colSpan=3>BBC bmx 1.1.0.0.0</TD></TR>
<TR>
<TD><I>Writing library :</I></TD>
<TD colSpan=3>libMXF (Win64) 1.1.0.0.0</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Video</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1001</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>AVC</TD></TR>
<TR>
<TD><I>Format/Info :</I></TD>
<TD colSpan=3>Advanced Video Codec</TD></TR>
<TR>
<TD><I>Format profile :</I></TD>
<TD colSpan=3>High 4:2:2 Intra@L5.2</TD></TR>
<TR>
<TD><I>Format settings, CABAC :</I></TD>
<TD colSpan=3>No</TD></TR>
<TR>
<TD><I>Format settings, GOP :</I></TD>
<TD colSpan=3>N=1</TD></TR>
<TR>
<TD><I>Format settings, wrapping mode :</I></TD>
<TD colSpan=3>Frame</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>0D01030102106001-0401020201323104</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>228 Mb/s</TD></TR>
<TR>
<TD><I>Width :</I></TD>
<TD colSpan=3>1 920 pixels</TD></TR>
<TR>
<TD><I>Height :</I></TD>
<TD colSpan=3>1 080 pixels</TD></TR>
<TR>
<TD><I>Display aspect ratio :</I></TD>
<TD colSpan=3>16:9</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Standard :</I></TD>
<TD colSpan=3>Component</TD></TR>
<TR>
<TD><I>Color space :</I></TD>
<TD colSpan=3>YUV</TD></TR>
<TR>
<TD><I>Chroma subsampling :</I></TD>
<TD colSpan=3>4:2:2</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>10 bits</TD></TR>
<TR>
<TD><I>Scan type :</I></TD>
<TD colSpan=3>Progressive</TD></TR>
<TR>
<TD><I>Bits/(Pixel*Frame) :</I></TD>
<TD colSpan=3>2.195</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>54.3 MiB (97%)</TD></TR>
<TR>
<TD><I>Title :</I></TD>
<TD colSpan=3>V1</TD></TR>
<TR>
<TD><I>Color range :</I></TD>
<TD colSpan=3>Limited</TD></TR>
<TR>
<TD><I>Color primaries :</I></TD>
<TD colSpan=3>BT.2020</TD></TR>
<TR>
<TD><I>Transfer characteristics :</I></TD>
<TD colSpan=3>HLG</TD></TR>
<TR>
<TD><I>Matrix coefficients :</I></TD>
<TD colSpan=3>BT.709</TD></TR>
<TR>
<TD><I>matrix_coefficients_Original :</I></TD>
<TD colSpan=3>BT.2020 non-constant</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Audio #1</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>2001</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>PCM</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>Little</TD></TR>
<TR>
<TD><I>Format settings, wrapping mode :</I></TD>
<TD colSpan=3>Frame (BWF)</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>0D01030102060100</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Bit rate mode :</I></TD>
<TD colSpan=3>Constant</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>2 304 kb/s</TD></TR>
<TR>
<TD><I>Channel(s) :</I></TD>
<TD colSpan=3>2 channels</TD></TR>
<TR>
<TD><I>Sampling rate :</I></TD>
<TD colSpan=3>48.0 kHz</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS (960 SPF)</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>24 bits</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>562 KiB (1%)</TD></TR>
<TR>
<TD><I>Title :</I></TD>
<TD colSpan=3>A1</TD></TR>
<TR>
<TD><I>Locked :</I></TD>
<TD colSpan=3>Yes</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Audio #2</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>2002</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>PCM</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>Little</TD></TR>
<TR>
<TD><I>Format settings, wrapping mode :</I></TD>
<TD colSpan=3>Frame (BWF)</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>0D01030102060100</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Bit rate mode :</I></TD>
<TD colSpan=3>Constant</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>2 304 kb/s</TD></TR>
<TR>
<TD><I>Channel(s) :</I></TD>
<TD colSpan=3>2 channels</TD></TR>
<TR>
<TD><I>Sampling rate :</I></TD>
<TD colSpan=3>48.0 kHz</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS (960 SPF)</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>24 bits</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>562 KiB (1%)</TD></TR>
<TR>
<TD><I>Title :</I></TD>
<TD colSpan=3>A2</TD></TR>
<TR>
<TD><I>Locked :</I></TD>
<TD colSpan=3>Yes</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Audio #3</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>2003</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>PCM</TD></TR>
<TR>
<TD><I>Format settings :</I></TD>
<TD colSpan=3>Little</TD></TR>
<TR>
<TD><I>Format settings, wrapping mode :</I></TD>
<TD colSpan=3>Frame (BWF)</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>0D01030102060100</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>2 s 0 ms</TD></TR>
<TR>
<TD><I>Bit rate mode :</I></TD>
<TD colSpan=3>Constant</TD></TR>
<TR>
<TD><I>Bit rate :</I></TD>
<TD colSpan=3>2 304 kb/s</TD></TR>
<TR>
<TD><I>Channel(s) :</I></TD>
<TD colSpan=3>2 channels</TD></TR>
<TR>
<TD><I>Sampling rate :</I></TD>
<TD colSpan=3>48.0 kHz</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS (960 SPF)</TD></TR>
<TR>
<TD><I>Bit depth :</I></TD>
<TD colSpan=3>24 bits</TD></TR>
<TR>
<TD><I>Stream size :</I></TD>
<TD colSpan=3>562 KiB (1%)</TD></TR>
<TR>
<TD><I>Title :</I></TD>
<TD colSpan=3>A3</TD></TR>
<TR>
<TD><I>Locked :</I></TD>
<TD colSpan=3>Yes</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Other #1</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>901-Material</TD></TR>
<TR>
<TD><I>Type :</I></TD>
<TD colSpan=3>Time code</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MXF TC</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Time code of first frame :</I></TD>
<TD colSpan=3>00:00:00:00</TD></TR>
<TR>
<TD><I>Time code of last frame :</I></TD>
<TD colSpan=3>00:00:01:49</TD></TR>
<TR>
<TD><I>Time code settings :</I></TD>
<TD colSpan=3>Material Package</TD></TR>
<TR>
<TD><I>Time code, stripped :</I></TD>
<TD colSpan=3>Yes</TD></TR>
<TR>
<TD><I>Title :</I></TD>
<TD colSpan=3>TC1</TD></TR></TBODY></TABLE><BR>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Other #2</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>901-Source</TD></TR>
<TR>
<TD><I>Type :</I></TD>
<TD colSpan=3>Time code</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>MXF TC</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>50.000 FPS</TD></TR>
<TR>
<TD><I>Time code of first frame :</I></TD>
<TD colSpan=3>00:00:00:00</TD></TR>
<TR>
<TD><I>Time code of last frame :</I></TD>
<TD colSpan=3>00:00:01:49</TD></TR>
<TR>
<TD><I>Time code settings :</I></TD>
<TD colSpan=3>Source Package</TD></TR>
<TR>
<TD><I>Time code, stripped :</I></TD>
<TD colSpan=3>Yes</TD></TR>
<TR>
<TD><I>Title :</I></TD>
<TD colSpan=3>TC1</TD></TR></TBODY></TABLE><BR>

As you can see, although the info in the header of the stream still says BT2020nc, the one in the container inserted by BMX says "BT.709", which, of course, is wrong.

**Comment by philipnbbc** [comment]
Good catch! I don't remember the reasoning for setting the BT709 defaults in that way in the code, but what I've done is change it so that the colormetry properties are extracted from the bitstream if available before defaulting to BT709. Let me know if that works for you.

**Comment by FranceBB** [comment]
Thank you for the swift reply.
I saw the code change https://github.com/bbc/bmx/pull/29/commits/20ea38e4cf4f81f65e441f413774c86628ae65ca
and that's exactly how it's supposed to be handled.
- If the bitstream already has properties, set them as the bitstream so that they're preserved
- else default to BT709.
Looks right to me. :)

Thank you! :)

**Comment by FranceBB** [comment]
In case anyone was interested in this scenario and needed an updated build with the latest commit by Philip, you can find it in attachment in this comment.

[build.zip](https://github.com/bbc/bmx/files/12576309/build.zip)
