### ISSUE TITLE
KLV Fill after header partition is less than minimum required value

### ISSUE THREAD

**Issue by philipnbbc** [bbc/bmx#37]
It was reported that it was less than 8KB (8192B) which is required for IMF. It should be 8192B plus a 256B margin in the implementation but maybe there is an issue.

**Comment by thomasheritage** [comment]
In the bmx-made IMF Image Track File I looked at the KLV Fill at the end of the Header Partition was 8047 bytes in total length (incl the length of the K&L&V of the KLV Fill item).

Note that SMPTE ST 2067-5:2020 says:
>  On creation, a minimum 8k-Byte fill shall follow the header partition to allow for in-place 
extension.

A couple of points:
* Technically "8k" would be 8000 bytes but it's not clear if that is what was meant
* I think the KLV Fill item will technically be considered to be part of the Header Partition -- given the definition of the Header Partition I don't think it's possible to have a KLV Fill _following_ it.

It's probably helpful for the KLV Fill at the end of the Header Partition to be clearly large enough (i.e. V of the KLV of the Fill item is at least 8192 bytes) to avoid any disputes.
