### ISSUE TITLE
mxf2raw: RDD 6 XML file has LF line endings in Windows

### ISSUE THREAD

**Issue by matthewmarks-bbc** [bbc/bmx#39]
I think it's producing LF instead of CRLF which would be the logical thing to do. However, there may be other instances where this occurs so if it's a significant refactoring than please wontfix.

**Comment by thomasheritage** [comment]
With a development tool like mxf2raw, I'd suggest it's a good thing if its outputs always use LF so that outputs are not platform dependent -- although various tools make different decisions on this I suppose

**Comment by matthewmarks-bbc** [comment]
Thanks - sounds sensible. No need to make changes here.
