### ISSUE TITLE
RDD 6 extraction: add `frames` suggestion to help

### ISSUE THREAD

**Issue by thomasheritage** [bbc/bmx#44]
`frames` commandline parameter processing was updated in #38 

After discussion with @matthewmarks-bbc:
However, it's still difficult for the user to know what the value should be. Perhaps just add a suggested value to the help e.g. `0-500`? (why not make it very large like this?) or `0-50`?

Is there any automatic checking that a complete description_text value has been extracted?

**Comment by philipnbbc** [comment]
I've created https://github.com/bbc/bmx/pull/45 that hopefully addresses this issue. It adds `0-500` as an example and the description goes into why a range is needed. There is automatic checking for a complete description text and the extraction process stops if all program description texts are complete.
