### ISSUE TITLE
raw2bmx wave / bwf input bitching about not being able to parse timstamp.

### ISSUE THREAD

**Issue by BoukeVahl** [bbc/bmx#57]
Warning: Failed to parse bext timestamp 
There seems nothing wrong with my BWF files.

Bouke

**Comment by philipnbbc** [comment]
It's warning that it failed to parse the contents of the `bext` chunk's `OriginationDate` and `OriginationTime` properties. What values are they set to?

**Comment by BoukeVahl** [comment]
Doh!
My bad! Date / Time was not set (0x).
The warning took my guard off, as I saw no TC in MC, where I was sure the timestamp was set. (Note, I refer to Timestamp in BWF as the 'TC' (Framecounter in samples.)
Thanks to you I've read the manual better, finding I missed -y 01:02:03:04 :-)
Sorry for the inconvenience!
