### ISSUE TITLE
SMPTE RDD 50 essence support (=DNxUncompressed)

### ISSUE THREAD

**Issue by mash-graz** [bbc/bmx#88]
Are there any efforts to support SMPTE RDD 50  (=DNxUncompressed) essence data in the foreseeable future?

It's a rather interesting kind of codec because it provides a wide range of very precise uncompressed image exchange options, which are otherwise only provided by image based formats like EXR. In the meanwhile it's supported as an in- and output option by many popular video productions solutions. It's a rather useful facility to read and write image data close to their actual floating point representation of nowadays GPU processing pipelines. This makes it a rather desirable option for QA, video technical research and advanced cross-application av-stream-pipelines.

Unfortunately there is no open source implementation of RDD 50 available util now and even the specification text isn't accessible freely.

**Comment by philipnbbc** [comment]
There are no plans to add support for DNxUncompressed. I see that it's basically a thin wrapper around raw uncompressed video frames providing dimension, fourcc packing type and interlace/progressive flag. It would be nice if it was accessible without having to pay $50.
