### ISSUE TITLE
raw2bmx - libMXF Error "disk file open new"

### ISSUE THREAD

**Issue by ndeshpande2022** [bbc/bmx#91]
Hi there,

I'm trying to create an MXF file with just an embedded timed-text track (IMSC 1.1). 
I've referenced the timed-text document in the docs folder here: [docs/timed_text.md](https://github.com/bbc/bmx/blob/main/docs/timed_text.md)

I've downloaded the latest windows version (that was attached as an asset to the version 1.2 release).

When I run the following command I get an error (which I think is related to the libMXF Dependency:

**Command:** 
raw2bmx.exe -t imf --dur 300 --tt C:\Users\natha\OneDrive\Documents\Dev\cc-cli\src\external\cc-lib\samples\mxf\manifest.txt

**Error:**
ERROR (libMXF): 'mxf_disk_file_open_new(filename.c_str(), &cFile)' failed, at libMXF++/libMXF++/File.cpp:93
ERROR: MXF exception caught: 'mxf_disk_file_open_new(filename.c_str(), &cFile)' failed, at libMXF++/libMXF++/File.cpp:93

**Manifest File:**
file: input.xml (this is in the same folder as the manifest file)
profile: imsc1.1/text
encoding: UTF-8
languages: en
start: 00:00:00:00

Any help would be much appreciated - thank you.

**Comment by philipnbbc** [comment]
It was reported by a user but I'd neglected to add the fix here. You need to use the `-o` option to set the output file, e.g. `-o output.mxf`.

It has now been fixed in the code in https://github.com/bbc/bmx/pull/93.

**Comment by ndeshpande2022** [comment]
Hi @philipnbbc,

I just wanted to confirm this has fixed our issue. Thank you very much!
